required-players: 20
startup-time: 5
lobby-spawn:
  world: 'world'
  x: 0
  y: 65
  z: 0
  yaw: 0
  pitch: 0
arenas:
  0:
    options:
      game-type: 'DEATHMATCH'
      points-to-win: 5
    spawn:
      world: 'world'
      x: 65
      y: 65
      z: 65
      yaw: 0
      pitch: 0
    teams:
      RED:
        spawn:
          world: 'world'
          x: 65
          y: 80
          z: 35
          yaw: 0
          pitch: 0
      BLUE:
        spawn:
          world: 'world'
          x: 65
          y: 80
          z: 75
          yaw: 180
          pitch: 0
  1:
    options:
      game-type: 'LASTSTANDING'
    spawn:
      world: 'world'
      x: 65
      y: 65
      z: 65
      yaw: 0
      pitch: 0