name: Duels
version: '${project.version}'
main: net.larskrs.plugins.duels.Duels
api-version: 1.18
description: Duels plugin
commands:
  duel:
permissions:
  simpleduels.bypass.build:
    description: bypass anti block break system.
    default: op
