name: SimpleDuels
version: '${project.version}'
main: net.larskrs.plugins.duels.Duels
api-version: 1.18
description: Duels plugin
commands:
  duel:
load: POSTWORLD
softdepend: ["Multiverse-Core"]
permissions:
  simpleduels.bypass.build:
    description: bypass anti block break system.
    default: op
  simpleduels.bypass.drop:
    description: bypass anti drop system.
    default: op
  simpleduels.admin:
    description: allows players to admin command...
    default: op
