required-players: 20
startup-time: 15
lobby-spawn:
  world: 'world'
  x: 0.5
  y: 65
  z: 0.5
  yaw: 0
  pitch: 0
arenas:
  1:
    sign:
      world: 'world'
      x: 66
      y: 102
      z: -24
      yaw: 0
      pitch: 0
    options:
      game-type: 'DEATHMATCH'
      points-to-win: 5
    spawn:
      world: 'world'
      x: -1.5
      y: 94
      z: -85.5
      yaw: 0
      pitch: 0
    teams:
      RED:
        spawn:
          world: 'world'
          x: -1.5
          y: 94
          z: -85.5
          yaw: 0
          pitch: 0
      BLUE:
        spawn:
          world: 'world'
          x: -1.5
          y: 94
          z: -23.5
          yaw: 180
          pitch: 0