name: Duels
version: '1.2.4'
main: net.larskrs.plugins.duels.Duels
api-version: 1.18
description: Duels plugin
commands:
  duel:
load: POSTWORLD
permissions:
  simpleduels.bypass.build:
    description: bypass anti block break system.
    default: op
  simpleduels.bypass.drop:
    description: bypass anti drop system.
    default: op
  simpleduels.command.reload:
    description: allows players to reload the config file. Admins...
    default: op
